{
 "title": "Yacht Stats",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "boat", "label": "Boats", "query": "SELECT title FROM boat" },
   {
    "name": "week",
    "query": "SELECT TO_CHAR(rent_start, 'DD-MM-YYYY') FROM price_point ORDER BY rent_start"
   },
   { "name": "region", "query": "select region from boat" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## Search Criteria\n\nWeekly charters every saturday from 2022-07-02 to 2022-08-27.\n\n    'destinations': 'split,sibenik,zadar',\n    'category': 'sailing-yacht',\n    'equipment': 'bow-thruster',\n    'cabins': '3',\n    'year': '2017-',\n    'boatLength': '12-14',\n    'currency': 'EUR',\n\nsee [Boataround API](https://api.boataround.com/#tag-Search)"
   }
  },
  {
   "title": "Avg Price of \"$boat\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT\navg(pp.total_price) as price,\ncount(pp) as \"number of free weeks\",\npp.created_at as time\nFROM boat as b join price_point pp on b.id=pp.boat_id\nWHERE $__timeFilter(pp.created_at) \nAND b.title = '$boat'\nAND TO_CHAR(pp.rent_start,'DD-MM-YYYY') in ($week)\ngroup by pp.created_at\n"
    }
   ]
  },
  { "title": "All Boats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Free Boat-Weeks for Season",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  pp.created_at as time,\n  count(pp.created_at) as value\nFROM\n  boat as b join price_point pp on b.id=pp.boat_id\nwhere\n $__timeFilter(pp.created_at)\n AND TO_CHAR(pp.rent_start,'DD-MM-YYYY') in ($week)\n AND b.region in ($region)\ngroup by\n pp.created_at\norder by time\n"
    }
   ]
  },
  {
   "title": "Free Boat-Weeks per Charter Agencies",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  count(pp) as value,\n  b.charter as metric\nFROM\n  boat as b join price_point pp on b.id=pp.boat_id\nwhere pp.created_at = (SELECT max(created_at) FROM price_point)\n AND TO_CHAR(pp.rent_start,'DD-MM-YYYY') in ($week)\n AND b.region in ($region)\ngroup by\n b.charter\n"
    }
   ]
  },
  {
   "title": "Free Boat-Weeks Price Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  avg(pp.total_price) as \"Rolling mainsail\"\nFROM\n  boat as b join price_point pp on b.id=pp.boat_id\nwhere\n pp.created_at = (SELECT max(created_at) FROM price_point)\n AND b.sail = 'Rolling mainsail'\n AND TO_CHAR(pp.rent_start,'DD-MM-YYYY') in ($week)\n AND b.region in ($region)\ngroup by b.boataround_ref, pp.rent_start\n \n"
    },
    {
     "rawSql": "SELECT\n  now() as time,\n  avg(pp.total_price) as \"Classical mainsail\"\nFROM\n  boat as b join price_point pp on b.id=pp.boat_id\nwhere\n pp.created_at = (SELECT max(created_at) FROM price_point)\n AND b.sail = 'Classical mainsail'\n AND TO_CHAR(pp.rent_start,'DD-MM-YYYY') in ($week)\n AND b.region in ($region)\ngroup by b.boataround_ref, pp.rent_start\n"
    }
   ]
  }
 ]
}